### PR TITLE
2004 data

### PR DESCRIPTION
**Pull request by Rub21**
cc. @olafveerman

### CODE REVIEW

**Comment by olafveerman** [comment]
This looks good. Do you want to add the `geoId` to this PR?

**Comment by Rub21** [comment]
@olafveerman  We added the geoIds!

**Comment by olafveerman** [comment]
Looking more closely at the results, it seems that votes are missing.

* in the original Excel, there are `8 024 538` valid votes.
* in the CSV of this PR, the sum of all votes is `7 219 136`.

I think these are the 'out-of-country' votes. Let's add them as special `provinces` without `geoId`.

**Comment by Rub21** [comment]
We added `Iran` and `Pakistan` in  the list

**Pull request merged**
